const countriesWithCurrencies = [
    { country: "Afghanistan", currencyName: "Afghan afghani", currencySymbol: "؋" },
    { country: "Albania", currencyName: "Albanian lek", currencySymbol: "Lek" },
    { country: "Algeria", currencyName: "Algerian dinar", currencySymbol: "د.ج" },
    { country: "Andorra", currencyName: "Euro", currencySymbol: "€" },
    { country: "Angola", currencyName: "Angolan kwanza", currencySymbol: "Kz" },
    { country: "Antigua and Barbuda", currencyName: "East Caribbean dollar", currencySymbol: "$" },
    { country: "Argentina", currencyName: "Argentine peso", currencySymbol: "$" },
    { country: "Armenia", currencyName: "Armenian dram", currencySymbol: "֏" },
    { country: "Australia", currencyName: "Australian dollar", currencySymbol: "$" },
    { country: "Austria", currencyName: "Euro", currencySymbol: "€" },
    { country: "Azerbaijan", currencyName: "Azerbaijani manat", currencySymbol: "₼" },
    { country: "Bahamas", currencyName: "Bahamian dollar", currencySymbol: "$" },
    { country: "Bahrain", currencyName: "Bahraini dinar", currencySymbol: "ب.د" },
    { country: "Bangladesh", currencyName: "Bangladeshi taka", currencySymbol: "৳" },
    { country: "Barbados", currencyName: "Barbadian dollar", currencySymbol: "$" },
    { country: "Belarus", currencyName: "Belarusian ruble", currencySymbol: "Br" },
    { country: "Belgium", currencyName: "Euro", currencySymbol: "€" },
    { country: "Belize", currencyName: "Belize dollar", currencySymbol: "$" },
    { country: "Benin", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Bhutan", currencyName: "Bhutanese ngultrum", currencySymbol: "Nu." },
    { country: "Bolivia", currencyName: "Bolivian boliviano", currencySymbol: "Bs." },
    { country: "Bosnia and Herzegovina", currencyName: "Bosnia and Herzegovina convertible mark", currencySymbol: "KM" },
    { country: "Botswana", currencyName: "Botswana pula", currencySymbol: "P" },
    { country: "Brazil", currencyName: "Brazilian real", currencySymbol: "R$" },
    { country: "Brunei", currencyName: "Brunei dollar", currencySymbol: "$" },
    { country: "Bulgaria", currencyName: "Bulgarian lev", currencySymbol: "лв" },
    { country: "Burkina Faso", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Burundi", currencyName: "Burundian franc", currencySymbol: "Fr" },
    { country: "Cabo Verde", currencyName: "Cape Verdean escudo", currencySymbol: "$" },
    { country: "Cambodia", currencyName: "Cambodian riel", currencySymbol: "៛" },
    { country: "Cameroon", currencyName: "Central African CFA franc", currencySymbol: "Fr" },
    { country: "Canada", currencyName: "Canadian dollar", currencySymbol: "$" },
    { country: "Central African Republic", currencyName: "Central African CFA franc", currencySymbol: "Fr" },
    { country: "Chad", currencyName: "Central African CFA franc", currencySymbol: "Fr" },
    { country: "Chile", currencyName: "Chilean peso", currencySymbol: "$" },
    { country: "China", currencyName: "Chinese yuan", currencySymbol: "¥" },
    { country: "Colombia", currencyName: "Colombian peso", currencySymbol: "$" },
    { country: "Comoros", currencyName: "Comorian franc", currencySymbol: "Fr" },
    { country: "Congo, Democratic Republic of the", currencyName: "Congolese franc", currencySymbol: "Fr" },
    { country: "Congo, Republic of the", currencyName: "Central African CFA franc", currencySymbol: "Fr" },
    { country: "Costa Rica", currencyName: "Costa Rican colón", currencySymbol: "₡" },
    { country: "Croatia", currencyName: "Croatian kuna", currencySymbol: "kn" },
    { country: "Cuba", currencyName: "Cuban peso", currencySymbol: "$" },
    { country: "Cyprus", currencyName: "Euro", currencySymbol: "€" },
    { country: "Czech Republic", currencyName: "Czech koruna", currencySymbol: "Kč" },
    { country: "Denmark", currencyName: "Danish krone", currencySymbol: "kr" },
    { country: "Djibouti", currencyName: "Djiboutian franc", currencySymbol: "Fr" },
    { country: "Dominica", currencyName: "East Caribbean dollar", currencySymbol: "$" },
    { country: "Dominican Republic", currencyName: "Dominican peso", currencySymbol: "$" },
    { country: "East Timor", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Ecuador", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Egypt", currencyName: "Egyptian pound", currencySymbol: "ج.م" },
    { country: "El Salvador", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Equatorial Guinea", currencyName: "Central African CFA franc", currencySymbol: "Fr" },
    { country: "Eritrea", currencyName: "Eritrean nakfa", currencySymbol: "Nkf" },
    { country: "Estonia", currencyName: "Euro", currencySymbol: "€" },
    { country: "Eswatini", currencyName: "Swazi lilangeni", currencySymbol: "E" },
    { country: "Ethiopia", currencyName: "Ethiopian birr", currencySymbol: "Br" },
    { country: "Fiji", currencyName: "Fijian dollar", currencySymbol: "$" },
    { country: "Finland", currencyName: "Euro", currencySymbol: "€" },
    { country: "France", currencyName: "Euro", currencySymbol: "€" },
    { country: "Gabon", currencyName: "Central African CFA franc", currencySymbol: "Fr" },
    { country: "Gambia", currencyName: "Gambian dalasi", currencySymbol: "D" },
    { country: "Georgia", currencyName: "Georgian lari", currencySymbol: "₾" },
    { country: "Germany", currencyName: "Euro", currencySymbol: "€" },
    { country: "Ghana", currencyName: "Ghanaian cedi", currencySymbol: "₵" },
    { country: "Greece", currencyName: "Euro", currencySymbol: "€" },
    { country: "Grenada", currencyName: "East Caribbean dollar", currencySymbol: "$" },
    { country: "Guatemala", currencyName: "Guatemalan quetzal", currencySymbol: "Q" },
    { country: "Guinea", currencyName: "Guinean franc", currencySymbol: "Fr" },
    { country: "Guinea-Bissau", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Guyana", currencyName: "Guyanese dollar", currencySymbol: "$" },
    { country: "Haiti", currencyName: "Haitian gourde", currencySymbol: "G" },
    { country: "Honduras", currencyName: "Honduran lempira", currencySymbol: "L" },
    { country: "Hungary", currencyName: "Hungarian forint", currencySymbol: "Ft" },
    { country: "Iceland", currencyName: "Icelandic króna", currencySymbol: "kr" },
    { country: "India", currencyName: "Indian rupee", currencySymbol: "₹" },
    { country: "Indonesia", currencyName: "Indonesian rupiah", currencySymbol: "Rp" },
    { country: "Iran", currencyName: "Iranian rial", currencySymbol: "﷼" },
    { country: "Iraq", currencyName: "Iraqi dinar", currencySymbol: "د.ع" },
    { country: "Ireland", currencyName: "Euro", currencySymbol: "€" },
    { country: "Israel", currencyName: "Israeli new shekel", currencySymbol: "₪" },
    { country: "Italy", currencyName: "Euro", currencySymbol: "€" },
    { country: "Jamaica", currencyName: "Jamaican dollar", currencySymbol: "$" },
    { country: "Japan", currencyName: "Japanese yen", currencySymbol: "¥" },
    { country: "Jordan", currencyName: "Jordanian dinar", currencySymbol: "د.أ" },
    { country: "Kazakhstan", currencyName: "Kazakhstani tenge", currencySymbol: "₸" },
    { country: "Kenya", currencyName: "Kenyan shilling", currencySymbol: "KSh" },
    { country: "Kiribati", currencyName: "Australian dollar", currencySymbol: "$" },
    { country: "Korea, North", currencyName: "North Korean won", currencySymbol: "₩" },
    { country: "Korea, South", currencyName: "South Korean won", currencySymbol: "₩" },
    { country: "Kosovo", currencyName: "Euro", currencySymbol: "€" },
    { country: "Kuwait", currencyName: "Kuwaiti dinar", currencySymbol: "د.ك" },
    { country: "Kyrgyzstan", currencyName: "Kyrgyzstani som", currencySymbol: "с" },
    { country: "Laos", currencyName: "Lao kip", currencySymbol: "₭" },
    { country: "Latvia", currencyName: "Euro", currencySymbol: "€" },
    { country: "Lebanon", currencyName: "Lebanese pound", currencySymbol: "ل.ل" },
    { country: "Lesotho", currencyName: "Lesotho loti", currencySymbol: "L" },
    { country: "Liberia", currencyName: "Liberian dollar", currencySymbol: "$" },
    { country: "Libya", currencyName: "Libyan dinar", currencySymbol: "د.ل" },
    { country: "Liechtenstein", currencyName: "Swiss franc", currencySymbol: "CHF" },
    { country: "Lithuania", currencyName: "Euro", currencySymbol: "€" },
    { country: "Luxembourg", currencyName: "Euro", currencySymbol: "€" },
    { country: "Madagascar", currencyName: "Malagasy ariary", currencySymbol: "Ar" },
    { country: "Malawi", currencyName: "Malawian kwacha", currencySymbol: "MK" },
    { country: "Malaysia", currencyName: "Malaysian ringgit", currencySymbol: "RM" },
    { country: "Maldives", currencyName: "Maldivian rufiyaa", currencySymbol: "Rf" },
    { country: "Mali", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Malta", currencyName: "Euro", currencySymbol: "€" },
    { country: "Marshall Islands", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Mauritania", currencyName: "Mauritanian ouguiya", currencySymbol: "MRU" },
    { country: "Mauritius", currencyName: "Mauritian rupee", currencySymbol: "₨" },
    { country: "Mexico", currencyName: "Mexican peso", currencySymbol: "$" },
    { country: "Micronesia", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Moldova", currencyName: "Moldovan leu", currencySymbol: "lei" },
    { country: "Monaco", currencyName: "Euro", currencySymbol: "€" },
    { country: "Mongolia", currencyName: "Mongolian tögrög", currencySymbol: "₮" },
    { country: "Montenegro", currencyName: "Euro", currencySymbol: "€" },
    { country: "Morocco", currencyName: "Moroccan dirham", currencySymbol: "د.م." },
    { country: "Mozambique", currencyName: "Mozambican metical", currencySymbol: "MT" },
    { country: "Myanmar", currencyName: "Burmese kyat", currencySymbol: "Ks" },
    { country: "Namibia", currencyName: "Namibian dollar", currencySymbol: "$" },
    { country: "Nauru", currencyName: "Australian dollar", currencySymbol: "$" },
    { country: "Nepal", currencyName: "Nepalese rupee", currencySymbol: "Rs" },
    { country: "Netherlands", currencyName: "Euro", currencySymbol: "€" },
    { country: "New Zealand", currencyName: "New Zealand dollar", currencySymbol: "$" },
    { country: "Nicaragua", currencyName: "Nicaraguan córdoba", currencySymbol: "C$" },
    { country: "Niger", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Nigeria", currencyName: "Nigerian naira", currencySymbol: "₦" },
    { country: "North Macedonia", currencyName: "Macedonian denar", currencySymbol: "ден" },
    { country: "Norway", currencyName: "Norwegian krone", currencySymbol: "kr" },
    { country: "Oman", currencyName: "Omani rial", currencySymbol: "ر.ع." },
    { country: "Pakistan", currencyName: "Pakistani rupee", currencySymbol: "Rs" },
    { country: "Palau", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Palestine", currencyName: "Israeli new shekel", currencySymbol: "₪" },
    { country: "Panama", currencyName: "Panamanian balboa", currencySymbol: "B/." },
    { country: "Papua New Guinea", currencyName: "Papua New Guinean kina", currencySymbol: "K" },
    { country: "Paraguay", currencyName: "Paraguayan guarani", currencySymbol: "₲" },
    { country: "Peru", currencyName: "Peruvian sol", currencySymbol: "S/" },
    { country: "Philippines", currencyName: "Philippine peso", currencySymbol: "₱" },
    { country: "Poland", currencyName: "Polish złoty", currencySymbol: "zł" },
    { country: "Portugal", currencyName: "Euro", currencySymbol: "€" },
    { country: "Qatar", currencyName: "Qatari riyal", currencySymbol: "ر.ق" },
    { country: "Romania", currencyName: "Romanian leu", currencySymbol: "lei" },
    { country: "Russia", currencyName: "Russian ruble", currencySymbol: "₽" },
    { country: "Rwanda", currencyName: "Rwandan franc", currencySymbol: "Fr" },
    { country: "Saint Kitts and Nevis", currencyName: "East Caribbean dollar", currencySymbol: "$" },
    { country: "Saint Lucia", currencyName: "East Caribbean dollar", currencySymbol: "$" },
    { country: "Saint Vincent and the Grenadines", currencyName: "East Caribbean dollar", currencySymbol: "$" },
    { country: "Samoa", currencyName: "Samoan tālā", currencySymbol: "WS$" },
    { country: "San Marino", currencyName: "Euro", currencySymbol: "€" },
    { country: "Sao Tome and Principe", currencyName: "São Tomé and Príncipe dobra", currencySymbol: "Db" },
    { country: "Saudi Arabia", currencyName: "Saudi riyal", currencySymbol: "ر.س" },
    { country: "Senegal", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Serbia", currencyName: "Serbian dinar", currencySymbol: "дин." },
    { country: "Seychelles", currencyName: "Seychellois rupee", currencySymbol: "₨" },
    { country: "Sierra Leone", currencyName: "Sierra Leonean leone", currencySymbol: "Le" },
    { country: "Singapore", currencyName: "Singapore dollar", currencySymbol: "$" },
    { country: "Slovakia", currencyName: "Euro", currencySymbol: "€" },
    { country: "Slovenia", currencyName: "Euro", currencySymbol: "€" },
    { country: "Solomon Islands", currencyName: "Solomon Islands dollar", currencySymbol: "$" },
    { country: "Somalia", currencyName: "Somali shilling", currencySymbol: "Sh" },
    { country: "South Africa", currencyName: "South African rand", currencySymbol: "R" },
    { country: "South Sudan", currencyName: "South Sudanese pound", currencySymbol: "£" },
    { country: "Spain", currencyName: "Euro", currencySymbol: "€" },
    { country: "Sri Lanka", currencyName: "Sri Lankan rupee", currencySymbol: "Rs" },
    { country: "Sudan", currencyName: "Sudanese pound", currencySymbol: "ج.س." },
    { country: "Suriname", currencyName: "Surinamese dollar", currencySymbol: "$" },
    { country: "Sweden", currencyName: "Swedish krona", currencySymbol: "kr" },
    { country: "Switzerland", currencyName: "Swiss franc", currencySymbol: "CHF" },
    { country: "Syria", currencyName: "Syrian pound", currencySymbol: "ل.س" },
    { country: "Taiwan", currencyName: "New Taiwan dollar", currencySymbol: "NT$" },
    { country: "Tajikistan", currencyName: "Tajikistani somoni", currencySymbol: "SM" },
    { country: "Tanzania", currencyName: "Tanzanian shilling", currencySymbol: "TSh" },
    { country: "Thailand", currencyName: "Thai baht", currencySymbol: "฿" },
    { country: "Togo", currencyName: "West African CFA franc", currencySymbol: "Fr" },
    { country: "Tonga", currencyName: "Tongan paʻanga", currencySymbol: "T$" },
    { country: "Trinidad and Tobago", currencyName: "Trinidad and Tobago dollar", currencySymbol: "$" },
    { country: "Tunisia", currencyName: "Tunisian dinar", currencySymbol: "د.ت" },
    { country: "Turkey", currencyName: "Turkish lira", currencySymbol: "₺" },
    { country: "Turkmenistan", currencyName: "Turkmenistani manat", currencySymbol: "T" },
    { country: "Tuvalu", currencyName: "Australian dollar", currencySymbol: "$" },
    { country: "Uganda", currencyName: "Ugandan shilling", currencySymbol: "USh" },
    { country: "Ukraine", currencyName: "Ukrainian hryvnia", currencySymbol: "₴" },
    { country: "United Arab Emirates", currencyName: "United Arab Emirates dirham", currencySymbol: "د.إ" },
    { country: "United Kingdom", currencyName: "Pound sterling", currencySymbol: "£" },
    { country: "United States", currencyName: "United States dollar", currencySymbol: "$" },
    { country: "Uruguay", currencyName: "Uruguayan peso", currencySymbol: "$" },
    { country: "Uzbekistan", currencyName: "Uzbekistani som", currencySymbol: "soʻm" },
    { country: "Vanuatu", currencyName: "Vanuatu vatu", currencySymbol: "Vt" },
    { country: "Vatican City", currencyName: "Euro", currencySymbol: "€" },
    { country: "Venezuela", currencyName: "Venezuelan bolívar", currencySymbol: "Bs." },
    { country: "Vietnam", currencyName: "Vietnamese đồng", currencySymbol: "₫" },
    { country: "Yemen", currencyName: "Yemeni rial", currencySymbol: "ر.ي" },
    { country: "Zambia", currencyName: "Zambian kwacha", currencySymbol: "ZK" },
    { country: "Zimbabwe", currencyName: "Zimbabwean dollar", currencySymbol: "$" }
];

    const select = document.getElementById("countries");
        
        // Create default option
        const defaultOption = document.createElement("option");
        defaultOption.text = "Select a country";
        defaultOption.value = "";
        select.appendChild(defaultOption);
    
        // Populate dropdown with country options
        countriesWithCurrencies.forEach(country => {
            const option = document.createElement("option");
            option.value = country.currencySymbol;
            option.text = country.currencyName;
            select.appendChild(option);
        });
      